image: node:8.0.0-alpine

cache:
  paths:
    - node_modules

build:
  stage: build
  artifacts:
    paths:
      - dist
  script:
    - npm install
    - npm run build

deploy:
  stage: deploy
  only:
    - master
  artifacts:
    paths:
      - dist
  script:
    - apk add --no-cache lftp
    - lftp -e "mirror -e -R dist $FTP_DIR" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_URL
