variables:
  NODE_IMAGE: node:lts-alpine

stages:
  - build
  - publish

build:
  image: $NODE_IMAGE
  stage: build
  cache:
    key: npm-cache
    paths:
      - .npm/
  artifacts:
    paths:
      - dist
    expire_in: 3 days
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run build

pages:
  image: $NODE_IMAGE
  stage: publish
  when: manual
  artifacts:
    paths:
      - public
    expire_in: 1 days
  script:
    - mkdir -p public
    - cp -r dist/* public
