export default {
  GET_COMING_SOON: 'GET_COMING_SOON',
  GET_COMING_SOON_TITLE: 'GET_COMING_SOON_TITLE',
  GET_SITE_TITLE: 'GET_SITE_TITLE',
  GET_EMAIL_ADRESS: 'GET_EMAIL_ADRESS',
  GET_GITHUB_URL: 'GET_GITHUB_URL',
  GET_LINKEDIN_URL: 'GET_LINKEDIN_URL',
};
