export default {
  COMING_SOON: 'COMING_SOON',
  COMING_SOON_TITLE: 'COMING_SOON_TITLE',
  SITE_TITLE: 'SITE_TITLE',
  EMAIL_ADRESS: 'EMAIL_ADRESS',
  GITHUB_URL: 'GITHUB_URL',
  LINKEDIN_URL: 'LINKEDIN_URL',
};
