export default {
  HOME: 'home',
  ABOUT: 'face',
  RESUME: 'featured_play_list',
  BLOG: 'book',
  PORTFOLIO: 'dashboard',
  CONTACT: 'face',
  PROFILE: 'person',
  LOGIN: 'person_outline',
  SHARE: 'share',
  CLOSE: 'close',
  SETTINGS: 'settings',
  SEARCH: 'search',
  LINK: 'link',
  MAIL: 'mail',
  SEND: 'send',
  SAVE: 'save',
  ADD: 'add',
  REMOVE: 'remove',
  RSS: 'rss_feed',
  DOWNLOAD: 'file_download',
  UPLOAD: 'file_upload',
  LESS: 'keyboard_arrow_up',
  MORE: 'keyboard_arrow_down',
  BEFORE: 'navigate_before',
  NEXT: 'navigate_next',
  EDIT: 'edit',
  ZOOM_IN: 'fullscreen',
  ZOOM_OUT: 'fullscreen_exit',
  IMPORTANT: 'priority_high',
  FACEBOOK: 'fab fa-facebook-f',
  GIT: 'fab fa-gitlab',
  LINKEDIN: 'fab fa-linkedin',
  STACKOVERFLOW: 'fab fa-stack-overflow',
  PHONE: 'phone',
};
