export default {
  COMING_SOON: 'COMING_SOON',
  COMING_SOON_TITLE: 'COMING_SOON_TITLE',
  SITE_TITLE: 'SITE_TITLE',
  EMAIL_ADRESS: 'EMAIL_ADRESS',
  GIT_URL: 'GIT_URL',
  LINKEDIN_URL: 'LINKEDIN_URL',
  REPOSITORIES: 'REPOSITORIES',
  LANGUAGES_COLOR: 'LANGUAGES_COLOR',
};
